steps:
  - imports:
      align: global
  - language_pragmas:
      style: vertical
      remove_redundant: true
  - simple_align:
      cases: true
      top_level_patterns: true
      records: true
  - trailing_whitespace: {}

# In recent stylish-haskell versions, record fields do not get aligned at all if any one of the fields length exceeds columns, so we pad it out from 80.
columns: 140

language_extensions:
  - MultiParamTypeClasses
  - TypeOperators
  - DataKinds
